package lv.sis.model;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class KursaDalibniekiTest {

    @Test
    void testNoArgsConstructor() {
        KursaDalibnieki d = new KursaDalibnieki();
        assertNotNull(d);
        assertEquals(0, d.getKdid()); // no setter, default int = 0
    }

    @Test
    void testConstructorWithAllParameters_setsAllFields() {
        KursaDalibnieki d = new KursaDalibnieki(
                "Jānis",
                "Bērziņš",
                "janis.berzins@test.com",
                "20000000",
                "PID_123",
                "Riga",
                "Latvija",
                "Brivibas 1",
                10,
                "LV-1010"
        );

        assertEquals(0, d.getKdid()); // generated by DB normally, in plain object stays 0

        assertEquals("Jānis", d.getVards());
        assertEquals("Bērziņš", d.getUzvards());
        assertEquals("janis.berzins@test.com", d.getEpasts());
        assertEquals("20000000", d.getTelefonaNr());
        assertEquals("PID_123", d.getPersonasId());
        assertEquals("Riga", d.getPilseta());
        assertEquals("Latvija", d.getValsts());
        assertEquals("Brivibas 1", d.getIelasNosaukumsNumurs());
        assertEquals(10, d.getDzivoklaNr());
        assertEquals("LV-1010", d.getPastaIndekss());
    }

    @Test
    void testSettersAndGetters_setsAllFields() {
        KursaDalibnieki d = new KursaDalibnieki();

        d.setVards("Anna");
        d.setUzvards("Kalniņa");
        d.setEpasts("anna@test.com");
        d.setTelefonaNr("29999999");
        d.setPersonasId("ABC-999");
        d.setPilseta("Liepaja");
        d.setValsts("Latvija");
        d.setIelasNosaukumsNumurs("Liela iela 5");
        d.setDzivoklaNr(25);
        d.setPastaIndekss("LV-3401");

        assertEquals("Anna", d.getVards());
        assertEquals("Kalniņa", d.getUzvards());
        assertEquals("anna@test.com", d.getEpasts());
        assertEquals("29999999", d.getTelefonaNr());
        assertEquals("ABC-999", d.getPersonasId());
        assertEquals("Liepaja", d.getPilseta());
        assertEquals("Latvija", d.getValsts());
        assertEquals("Liela iela 5", d.getIelasNosaukumsNumurs());
        assertEquals(25, d.getDzivoklaNr());
        assertEquals("LV-3401", d.getPastaIndekss());
    }

    @Test
    void testNullableFields_canBeNull() {
        KursaDalibnieki d = new KursaDalibnieki();

        d.setDzivoklaNr(null);
        d.setPastaIndekss(null);
        d.setSertifikati(null);
        d.setVertejumi(null);
        d.setAvgGrade(null);

        assertNull(d.getDzivoklaNr());
        assertNull(d.getPastaIndekss());
        assertNull(d.getSertifikati());
        assertNull(d.getVertejumi());
        assertNull(d.getAvgGrade());
    }

    @Test
    void testCollections_setAndGet() {
        KursaDalibnieki d = new KursaDalibnieki();

        ArrayList<Sertifikati> sertifikati = new ArrayList<>();
        ArrayList<Vertejumi> vertejumi = new ArrayList<>();

        d.setSertifikati(sertifikati);
        d.setVertejumi(vertejumi);

        assertSame(sertifikati, d.getSertifikati());
        assertSame(vertejumi, d.getVertejumi());
    }

    @Test
    void testAvgGrade_setAndGet() {
        KursaDalibnieki d = new KursaDalibnieki();

        d.setAvgGrade(8.5f);
        assertEquals(8.5f, d.getAvgGrade());
    }

    @Test
    void testToString_doesNotThrow() {
        KursaDalibnieki d = new KursaDalibnieki();
        assertDoesNotThrow(d::toString);
    }
}